### ISSUE TITLE
cmake doesn't find path to include file #include "CmdLineArgParser.h"

### ISSUE THREAD

**Issue by mdkeehan** [pletzer/fidibench#2]
I just tried a git clone, mkdir build, cd build, cmake .., make and got the following error

```
/home/mike/git/fidibench/laplacian/cxx/testStencil2d.cxx:55: undefined reference to `bool CmdLineArgParser::get<bool>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
```

I think the error is caused by cmake not including the path to the c++ include files.

**Comment by pletzer** [comment]
Thanks @mdkeehan for finding the issue. On it...

**Comment by pletzer** [comment]
This has been fixed.

**Comment by mdkeehan** [comment]
Cool it now compiles on my machine.
